### ISSUE TITLE
About naming conventions in Go

### ISSUE THREAD

**Issue by rayz-bee** [taodanfang/gokit-microservices-template#1]
感谢分享的文章，有点疑惑为什么所有函数的命名没有采用Go官方约定俗成的驼峰式命名方式

**Comment by x-noteboard** [comment]
个人喜好，不太喜欢驼峰命名。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taodanfang/gokit-microservices-template"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月4日(星期三) 下午4:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[taodanfang/gokit-microservices-template] About naming conventions in Go (#1)





 
感谢分享的文章，有点疑惑为什么所有函数的命名没有采用Go官方约定俗成的驼峰式命名方式
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
